Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SIPVS_NT.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Validation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Cryptography.Xml;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;
using System.Globalization;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Numerics;


namespace SIPVS_NT.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]

    // Logger class for logging
    public class Logger
    {
        private readonly string logFilePath;

        public Logger(string logFilePath)
        {
            this.logFilePath = logFilePath;

            // Create or overwrite the log file at the start of the program
            File.Create(logFilePath).Close();
        }

        public void Log(string message)
        {
            try
            {
                // Append to the log file
                using (StreamWriter sw = File.AppendText(logFilePath))
                {
                    // if needed, you can add a timestamp to the message
                    sw.WriteLine(message);
                }
            }
            catch (Exception ex)
            {
                // Handle exceptions, for example, print to console
                Console.WriteLine($"Error logging: {ex.Message}");
            }
        }
    }


    public class ValidationModel : PageModel
    {
        // Folder path where the files are located
        private readonly string folderPath = "signatures";

        // Specify the path for the log file
        private readonly string logFilePath = "validation_results.log";
        private string timestampCrlUrl = "http://test.ditec.sk/TSAServer/crl/dtctsa.crl";
        private string signCrlUrl = "http://test.ditec.sk/DTCCACrl/DTCCACrl.crl";

        public IActionResult OnPostLoadFile(IFormFile uploadedFile)
        {
            if (uploadedFile != null && uploadedFile.Length > 0)
            {
                // Determine a temporary folder path
                string tempFolderPath = Path.Combine(Path.GetTempPath(), "signatures_temp");

                // Ensure the folder exists, create it if not
                if (!Directory.Exists(tempFolderPath))
                {
                    Directory.CreateDirectory(tempFolderPath);
                }

                // Construct the full path for saving the file temporarily
                string tempFilePath = Path.Combine(tempFolderPath, uploadedFile.FileName);

                // Save the file to the temporary location
                using (var fileStream = new FileStream(tempFilePath, FileMode.Create))
                {
                    uploadedFile.CopyTo(fileStream);
                }

                Logger logger = new Logger(logFilePath);

                // Validate the file using the file path
                Validate(logger, uploadedFile.FileName, tempFilePath);

                return Content(
                    $"<script>alert('Validacia sa dokoncila pre {uploadedFile.FileName}'); window.location.href='/Validation'</script>",
                    "text/html");
            }
            else
            {
                return Content(
                    "<script>alert('Je potrebne nahrat subor.'); window.location.href='/Validation'</script>",
                    "text/html");
                ;
            }
        }

        // Event handler for the button click
        public IActionResult OnPostLoadFiles()
        {
            try
            {
                // Create an instance of the Logger
                Logger logger = new Logger(logFilePath);

                // Get all files in the folder
                //string[] files = Directory.GetFiles(folderPath);
                string[] files = Directory.GetFiles(folderPath).OrderBy(f => f).ToArray();

                // Loop through each file
                foreach (var filePath in files)
                {
                    // get file name
                    string fileName = Path.GetFileName(filePath);
                    Validate(logger, fileName, filePath);
                }

                // Logic or return a response if needed
                return Content("<script>alert('Validacia je dokoncena.'); window.location.href='/Validation'</script>",
                    "text/html");
            }
            catch (Exception ex)
            {
                // Handle exceptions, return an error response
                return new BadRequestObjectResult($"Error validating signatures: {ex.Message}");
            }
        }


        // add here a function for validation

        private void Validate(Logger logger, string fileName, string filePath)
        {
            logger.Log("\n--------------------------------------------------");
            logger.Log($"Validácia súboru: {fileName}");

            // Initialize the verification flag
            bool validationPassed = true;


            // Verify conditions one by one
            // Verification of the data envelope - Overenie dátovej obálky
            if (!DataEnvelope(filePath, "xzep", "http://www.ditec.sk/ep/signature_formats/xades_zep/v1.0"))
            {
                validationPassed = false;
                logger.Log(
                    $"Overenie dátovej obálky nebolo úspešné - neplatná hodnota atribútu xmlns:xzep v koreňovom prvku.");
                return; // Stop verification for this file
            }

            if (!DataEnvelope(filePath, "ds", "http://www.w3.org/2000/09/xmldsig#"))
            {
                validationPassed = false;
                logger.Log(
                    $"Overenie dátovej obálky nebolo úspešné - neplatná hodnota atribútu xmlns:ds v koreňovom prvku.");
                return; // Stop verification for this file
            }

            // Verification XML Signature 
            if (!Signature(filePath, logger))
            {
                validationPassed = false;
                //logger.Log($"Overenie XML Signature nebolo úspešné pre: {filePath}");
                return; // Stop verification for this file
            }

            // Verification Core Validation 
            if (!CoreValidation(filePath, logger))
            {
                validationPassed = false;
                //logger.Log($"Overenie Core Validation nebolo úspešné ");
                return; // Stop verification for this file
            }

            // verification of other elements
            if (!CheckElements(filePath, logger))
            {
                validationPassed = false;
                //logger.Log($"Overenie other elements nebolo úspešné pre: {filePath}");
                return; // Stop verification for this file
            }

            if (!checkTimestamp(filePath))
            {
                validationPassed = false;
                logger.Log($"Overenie časovej pečiatky nebolo úspešné.");
                return; // Stop verification for this file
            }

            if (!checkMessageImprint(filePath))
            {
                validationPassed = false;
                logger.Log($"Overenie Messageimprint nebolo úspešné voči podpisu.");
                return; // Stop verification for this file
            }

            if (!checkSignCert(filePath))
            {
                validationPassed = false;
                logger.Log($"Overenie platnosti podpisového certifikátu nebolo úspešné.");
                return; // Stop verification for this file
            }

            // pridanie dalsieho overenia

            // If all conditions passed, log successful validation
            if (validationPassed)
            {
                logger.Log($"Súbor bol úspešne validovaný: {fileName}");
            }
        }

        // Method for verifying the data envelope - Overenie dátovej obálky
        private bool DataEnvelope(string filePath, string prefix, string expectedUri)
        {
            // Load XML content from the file
            XDocument xmlDoc = XDocument.Load(filePath);
            // Get the root element
            XElement rootElement = xmlDoc.Root;

            XAttribute namespaceAttribute = rootElement.Attribute(XNamespace.Xmlns + prefix);

            if (namespaceAttribute == null || namespaceAttribute.Value != expectedUri)
            {
                return false;
            }

            return true;
        }

        // Method for verifying the XML Signature
        private bool Signature(string filePath, Logger logger)
        {
            string[] SUPPORTED_SIGNATURE_ALGORITHMS =
            {
                "http://www.w3.org/2000/09/xmldsig#dsa-sha1",
                "http://www.w3.org/2000/09/xmldsig#rsa-sha1",
                "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                "http://www.w3.org/2001/04/xmldsig-more#rsa-sha384",
                "http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"
            };

            string[] SUPPORTED_DIGEST_ALGORITHMS =
            {
                "http://www.w3.org/2000/09/xmldsig#sha1",
                "http://www.w3.org/2001/04/xmldsig-more#sha224",
                "http://www.w3.org/2001/04/xmlenc#sha256",
                "https://www.w3.org/2001/04/xmldsig-more#sha384",
                "http://www.w3.org/2001/04/xmlenc#sha512"
            };

            string[] SUPPORTED_TRANSFORM_ALGORITHMS =
            {
                "http://www.w3.org/TR/2001/REC-xml-c14n-20010315",
                "http://www.w3.org/2000/09/xmldsig#base64"
            };

            // Load XML content from the file
            XDocument xmlDoc = XDocument.Load(filePath);

            // Define the namespace
            var namespaceId = new XmlNamespaceManager(new NameTable());
            namespaceId.AddNamespace("ds", "http://www.w3.org/2000/09/xmldsig#");

            // checking the contents of ds:SignatureMethod a ds:CanonicalizationMethod 
            string signatureMethodAlgorithm = xmlDoc

Pages/Index.cshtml
@page
@using System.Web
@model IndexModel
@{
    ViewData["Title"] = "Formulár";
}


<!DOCTYPE html>
<html lang="sk">

<head>
    <script type="text/javascript" src="https://www.slovensko.sk/static/zep/dbridge_js/v1.0/config.js"></script>
    <script type="text/javascript" src="https://www.slovensko.sk/static/zep/dbridge_js/v1.0/dCommon.min.js"></script>
    <script type="text/javascript" src="https://www.slovensko.sk/static/zep/dbridge_js/v1.0/dSigXades.min.js"></script>
    <title>Formulár pre účastníkov</title>
</head>

<body>
    <form method="post">
        <fieldset>
            <legend>Účastníci</legend>
            <ul id="ucastnici">
                <!-- Existing participants will be displayed here -->
            </ul>
            <button type="button" id="pridat-ucastnika">Pridať účastníka</button>
            <button type="submit" id="odoslat-posledny-ucastnik">Ulož XML</button>
            <button type="submit" name="generateHtml">Transformuj XML do HTML</button>
            <p></p>
            <button type="submit" name="addTimestamp">Pridaj časovú pečiatku</button>
        </fieldset>
    </form>
    <br>
    <fieldset>
        <form method="post" asp-page-handler="UploadXml">
            <button type="submit">Porovnaj XML voči XSD</button>
        </form>
    </fieldset>
    <br>
    <fieldset>
    <form>
            <button type="button" id="podpisovac">Podpíš</button>
    </form>
    </fieldset>
    <script>
        // počiatočná hodnota počtu účastníkov
        let pocet_ucastnikov = 1;

        // funkcia na pridanie nového účastníka
        function pridatUcastnika() {

            // kontrola, či je počet účastníkov menší ako 10
            if (pocet_ucastnikov > 10) {
                // zablokovanie tlačidla "Pridať účastníka"
                alert("Maximálny počet účastníkov je 10.");
                return;
            }

            // vytvorenie nového prvku <li>
            let novyUcastnik = document.createElement("li");

            // pridanie potrebných polí
            novyUcastnik.innerHTML = `
                <h2>Účastník ${pocet_ucastnikov}</h2>
                <label for="Participants[${pocet_ucastnikov}].Name">Meno:</label>
                <input type="text" name="Participants[${pocet_ucastnikov}].Name" id="ucastnik_${pocet_ucastnikov}_meno" required pattern="^[a-zA-ZÀ-ž]+$">
                <label for="Participants[${pocet_ucastnikov}].Surname">Priezvisko:</label>
                <input type="text" name="Participants[${pocet_ucastnikov}].Surname" id="ucastnik_${pocet_ucastnikov}_priezvisko" required pattern="^[a-zA-ZÀ-ž]+$">
                <label for="Participants[${pocet_ucastnikov}].Date">Dátum narodenia:</label>
                <input type="date" name="Participants[${pocet_ucastnikov}].Date" id="ucastnik_${pocet_ucastnikov}_datum_narodenia" required  onchange="calculateAge(this)">
                <label for="Participants[${pocet_ucastnikov}].Age">Vek:</label>
                <input type="number" name="Participants[${pocet_ucastnikov}].Age" id="ucastnik_${pocet_ucastnikov}_vek" required min="0" max="120">
                <label for="Participants[${pocet_ucastnikov}].Email">E-mail:</label>
                <input type="email" name="Participants[${pocet_ucastnikov}].Email" id="ucastnik_${pocet_ucastnikov}_email" placeholder="me@example.com" required>
            `;

            // pridanie nového prvku na koniec zoznamu
            document.getElementById("ucastnici").appendChild(novyUcastnik);

            // zvýšenie počtu účastníkov
            pocet_ucastnikov++;
        }

        document.getElementById("pridat-ucastnika").addEventListener("click", pridatUcastnika);
    </script>





    @if (TempData["result"] != null)
    {
        <script>
            // Check if TempData["result"] is not null
            var resultMessage = "@TempData["result"]";

            // Create a temporary element to decode HTML entities
            var tempElement = document.createElement("div");
            tempElement.innerHTML = resultMessage;
            var decodedMessage = tempElement.textContent;

            if (decodedMessage.trim() !== "") {
                alert(decodedMessage);
            }
        </script>
    }

    @if (ViewData["PopupMessage"] != null)
    {
        <script>
            // Check if ViewData["PopupMessage"] is not null
            var resultMessage = "@ViewData["PopupMessage"]";

            // Create a temporary element to decode HTML entities
            var tempElement = document.createElement("div");
            tempElement.innerHTML = resultMessage;
            var decodedMessage = tempElement.textContent;

            if (decodedMessage.trim() !== "") {
                alert(decodedMessage);
            }
        </script>
    }

    <script>


        function vytvoritHtml() {
            // Fetch the XML file
            fetch('ucastnici.xml')
                .then(response => response.text())
                .then(xmlData => {
                    // Fetch the XSLT file
                    fetch('ucastnici.xslt')
                        .then(response => response.text())
                        .then(xsltData => {
                            // Transform XML to HTML using XSLT
                            const xsltProcessor = new XSLTProcessor();
                            const parser = new DOMParser();
                            const xml = parser.parseFromString(xmlData, 'text/xml');
                            const xsl = parser.parseFromString(xsltData, 'text/xml');
                            const resultDocument = xsltProcessor.transformToDocument(xml, xsl);
                            const htmlData = new XMLSerializer().serializeToString(resultDocument);

                            // Create an HTML blob and object URL
                            const blob = new Blob([htmlData], { type: 'text/html' });
                            const objectUrl = URL.createObjectURL(blob);

                            // Create a download link for the HTML file
                            const a = document.createElement('a');
                            a.href = objectUrl;
                            a.download = 'ucastnici_html.html';
                            a.textContent = 'Download HTML';

                            // Append the link to the document
                            document.body.appendChild(a);
                        })
                        .catch(error => {
                            console.error('Error fetching XSLT file:', error);
                        });
                })
                .catch(error => {
                    console.error('Error fetching XML file:', error);
                });
        }

        // Add an event listener to the "Transformuj do HTML" button
        document.getElementById("transformuj-do-html").addEventListener("click", vytvoritHtml);
    </script>
    <script>
        function calculateAge(dateInput) {
            const today = new Date();
            const birthDate = new Date(dateInput.value);

            // Check if the entered date is in the future
            if (birthDate > today) {
                alert("Dátum narodenia nemôže byť v budúcnosti.");
                dateInput.value = ""; // Clear the input
                return;
            }

            let age = today.getFullYear() - birthDate.getFullYear();

            // If the birthday hasn't occurred yet this year, subtract one year
            if (today.getMonth() < birthDate.getMonth() || (today.getMonth() === birthDate.getMonth() && today.getDate() < birthDate.getDate())) {
                age--;
            }

            // Update the age input field with the calculated age
            const ageInputId = dateInput.id.replace("datum_narodenia", "vek");
            document.getElementById(ageInputId).value = age;
        }
    </script>
    @{
        // Obtain the Base64 content using your C# method
        var base64Content = LoadPdf.LoadFileAsBase64("example.pdf");
        var encodedBase64Content = HttpUtility.UrlEncode(base64Content);
    }
    <script>
        // Define the Callback function
        function Callback(onSuccess) {
            this.onSuccess = onSuccess;
            this.onError = function (e) {
                alert("Chyba: " + e);
            };
        }

async function executeScript() {
  const xmlData = await loadXML();
  const xsdData = await loadXSD();
  const xslData = await loadXSL();
  ditec.dSigXadesJs.deploy(null, new Callback(function () {
    ditec.dSigXadesJs.initialize(new Callback(async function () {
      await ditec.dSigXadesJs.addPdfObject("objectPdf", "pdf", decodeURIComponent("@encodedBase64Content"), "", "http://example.com/objectFormatIdentifier", 2, false);
      await ditec.dSigXadesJs.addXmlObject2("objectXml", "xml", xmlData, xsdData, "http://SIPVS_I_NT_ucastnici_skupina_6", "http://localhost:5057/?handler=xsdData", xslData, "http://localhost:5057/?handler=xslData", "HTML");
      await ditec.dSigXadesJs.sign20("signatureId", "http://www.w3.org/2001/04/xmlenc#sha256", "urn:oid:1.3.158.36061701.1.2.3", "dataEnvelopeId", "http://dataEnvelopeURI", "dataEnvelopeDescr");

      ditec.dSigXadesJs.getSignedXmlWithEnvelope(new Callback(function (ret) {
          if (ret == null || ret === '') {
              alert("Chyba pri podpisovaní");
          }
          else {
              // returned signed document
              // Format XML
              const xmlDoc = new DOMParser().parseFromString(ret, 'text/xml');
              const serializer = new XMLSerializer();
              const formattedXML = serializer.serializeToString(xmlDoc);
        
              // Save XML to a new file
              const blob = new Blob([formattedXML], { type: 'text/xml' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = 'signed.xml';
              a.click();
              URL.revokeObjectURL(url);
            }
      }));
    }));
  }));
}


        // Attach a click event listener to the button
        document.getElementById("podpisovac").addEventListener("click", executeScript);


        async function loadXML() {
            try {
                const response = await fetch('?handler=XmlData');
                const xmlText = await response.text();
                return xmlText;


            } catch (error) {
                console.error('Error loading XML:', error);
            }
        }

        async function loadXSD() {
            try {
                const response = await fetch('?handler=XsdData');
                const xsdText = await response.text();
                console.log(xsdText)
                return xsdText;


            } catch (error) {
                console.error('Error loading XML:', error);
            }
        }

        async function loadXSL() {
            try {
                const response = await fetch('?handler=XslData');
                const xslText = await response.text();
                console.log(xslText)
                return xslText;


            } catch (error) {
                console.error('Error loading XML:', error);
            }
        }

    </script>

</body>

</html>

Pages/Validation.cshtml
@page
@model ValidationModel
@{
    ViewData["Title"] = "Validation";
}

<h2>Validácia</h2>
<p>
    Tlačidlo, ktorým sa spúšťa validácia.
</p>

<form method="post">
    <button type="submit" asp-page-handler="LoadFiles" class="btn btn-secondary" style="background-color: black; outline-color: black; ">Over všetky súbory</button>
</form>

<p> </p>

<form method="post" enctype="multipart/form-data">
    <input type="file" name="uploadedFile" />
    <p> </p>
    <button type="submit" asp-page-handler="LoadFile" class="btn btn-secondary" style="background-color: black; outline-color: black; ">Over jeden súbor</button>
</form>